class Solution:
    def maxProfit(self, prices: List[int]) -> int:
        '''
            Understand: 
                Input: Array with numbers representing the prices of stock NeetCoin
                Ouput: Max profit possible based on the historical list of prices.
                Blackbox: Find the best profit based on the margin generated by purchase and selling at later time
                Observation:
                    If first price then set buy to first price and sell to first price
                    Calculate profit every time we find a better sell
            Match:
                Two pointers
            Plan:
                Initiate a pointer to track the buy time
                Initiate a pointer to track the sell time
                while the sell is in bounds:
                    If current price is lower than buy then update buy to be this price as well as sell
                    If current price is greater than sell then update sell to be this one
                    At the end always calcualte the profit and update the profit to be the max of current buy-sell profit and max_profit
            Implement:
            Review:
            Evaluate
        '''
        max_profit = 0
        buy = 0
        sell = 0
        for curr in range(len(prices)):
            if prices[curr] < prices[buy]:
                buy = curr
                sell = curr
            if prices[curr] > prices[sell]:
                sell = curr
            max_profit = max(prices[sell] - prices[buy], max_profit) 
        return max_profit